language: node_js
node_js:
- stable
install:
- npm install -g khaos
- khaos install localytics/slackbot-scaffold slackbot
- pushd ~/.khaos/slackbot
- git fetch origin +refs/pull/$TRAVIS_PULL_REQUEST/merge
- git checkout -qd FETCH_HEAD
- popd
- yes test | khaos create slackbot testbot
- pushd testbot/nodejs
- npm install
- popd
script:
- pushd testbot/nodejs
- npm test
- popd
