language: node_js
node_js:
- stable
install:
- npm install -g khaos
- khaos install localytics/slackbot-scaffold slackbot
- pushd ~/.khaos/slackbot
- echo $TRAVIS_COMMIT
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PULL_REQUEST
- git checkout $TRAVIS_COMMIT
- popd
- yes test | khaos create slackbot testbot
- pushd testbot/nodejs
- npm install
- popd
script:
- pushd testbot/nodejs
- npm test
- popd
